markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Brian Kirsten
url: http://briankirsten.com
description: The Monkey King's domain.
twitter: bkirsten
github: briankirsten
gravatar_url: http://fictfactuserimages.fictfact.com/15b949e7-f91d-4c2b-a0bd-71beb71fc788.jpg